import json
import numpy as np
from pathlib import Path

BASE = Path(r"d:\Huhb\AIProject\Huhb-Utopia-Project\Huhb-Viewer-ThreeAIExtend\Huhb3D-Viewer-AIHelper-RoboDataSynthesizer\sell_Huhb3D-Test-Precision-v4")
OUTPUT = BASE / "ros_deployment_manual.txt"

lines = []
def p(s=""):
    lines.append(s)

p("=" * 80)
p("  Huhb3D ROS Deployment Manual")
p("  cv_bridge + image_transport + depth_image_proc")
p("=" * 80)

p()
p("SECTION 1: PREREQUISITES")
p("-" * 80)
p()
p("  ROS2 packages required:")
p("    sudo apt install ros-${ROS_DISTRO}-cv-bridge \\")
p("                     ros-${ROS_DISTRO}-image-transport \\")
p("                     ros-${ROS_DISTRO}-depth-image-proc \\")
p("                     ros-${ROS_DISTRO}-image-pipeline")
p()
p("  Python dependencies:")
p("    pip install opencv-python numpy rosbag2")
p()
p("  Dataset structure on ROS workstation:")
p("    ~/huhb3d_dataset/")
p("    |-- dataset_metadata.json")
p("    |-- flange/")
p("    |   |-- scene_camera.json")
p("    |   |-- scene_gt.json")
p("    |   |-- rgb/rgb_0001.png ... rgb_0010.png")
p("    |   |-- depth/depth_0001.png ... depth_0010.png")
p("    |   |-- mask/ ...")
p("    |   |-- mask_instance/ ...")
p("    |-- bearing_block/")
p("    |-- ...")

p()
p("SECTION 2: READING DEPTH MAPS - THE CRITICAL PATH")
p("-" * 80)
p()
p("  *** THE #1 CAUSE OF BLACK DEPTH IMAGES IS WRONG imread FLAG ***")
p()
p("  CORRECT:")
p("    import cv2")
p("    depth = cv2.imread('depth_0001.png', cv2.IMREAD_UNCHANGED)")
p("    # depth.shape = (600, 800), depth.dtype = uint16")
p("    # depth values: 730-844 (mm)")
p()
p("  WRONG - produces BLACK IMAGE:")
p("    depth = cv2.imread('depth_0001.png')  # default = IMREAD_COLOR")
p("    # depth.shape = (600, 800, 3), depth.dtype = uint8")
p("    # depth values: 2-3 (high byte LOST!)")
p()
p("  WRONG - produces WRONG VALUES:")
p("    depth = cv2.imread('depth_0001.png', cv2.IMREAD_GRAYSCALE)")
p("    # depth.shape = (600, 800), depth.dtype = uint8")
p("    # depth values: 2-3 (high byte LOST, 99.7% error!)")
p()
p("  Why this happens:")
p("    Our depth PNGs are 16-bit grayscale (bit_depth=16, color_type=0).")
p("    - IMREAD_UNCHANGED preserves the original 16-bit format")
p("    - IMREAD_COLOR converts to 8-bit BGR (3 channels)")
p("    - IMREAD_GRAYSCALE converts to 8-bit (high byte truncated)")
p("    Values 730-844 in uint16 become 2-3 in uint8 (730>>8=2, 844>>8=3)")

p()
p("SECTION 3: DISPLAYING DEPTH MAPS WITH imshow")
p("-" * 80)
p()
p("  *** cv2.imshow CANNOT directly display uint16 depth maps ***")
p()
p("  WRONG - shows black image:")
p("    depth = cv2.imread('depth_0001.png', cv2.IMREAD_UNCHANGED)")
p("    cv2.imshow('depth', depth)  # BLACK! values 730-844 look near-zero vs 65535")
p("    cv2.waitKey(0)")
p()
p("  CORRECT - normalize before display:")
p("    depth = cv2.imread('depth_0001.png', cv2.IMREAD_UNCHANGED)")
p("    depth_display = cv2.normalize(depth, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)")
p("    cv2.imshow('depth', depth_display)")
p("    cv2.waitKey(0)")
p()
p("  CORRECT - colormap for better visualization:")
p("    depth = cv2.imread('depth_0001.png', cv2.IMREAD_UNCHANGED)")
p("    depth_display = cv2.normalize(depth, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)")
p("    depth_color = cv2.applyColorMap(depth_display, cv2.COLORMAP_JET)")
p("    cv2.imshow('depth_colormap', depth_color)")
p("    cv2.waitKey(0)")
p()
p("  CORRECT - with background masking:")
p("    depth = cv2.imread('depth_0001.png', cv2.IMREAD_UNCHANGED)")
p("    mask = depth > 0")
p("    depth_norm = np.zeros_like(depth, dtype=np.uint8)")
p("    depth_norm[mask] = ((depth[mask] - depth[mask].min()) /")
p("                        (depth[mask].max() - depth[mask].min()) * 255).astype(np.uint8)")
p("    cv2.imshow('depth_masked', depth_norm)")
p("    cv2.waitKey(0)")

p()
p("SECTION 4: cv_bridge - DEPTH TO sensor_msgs/Image")
p("-" * 80)
p()
p("  Publishing depth as ROS Image:")
p()
p("    import rclpy")
p("    from rclpy.node import Node")
p("    from sensor_msgs.msg import Image")
p("    from cv_bridge import CvBridge")
p("    import cv2")
p()
p("    class DepthPublisher(Node):")
p("        def __init__(self):")
p("            super().__init__('depth_publisher')")
p("            self.bridge = CvBridge()")
p("            self.pub = self.create_publisher(Image, '/camera/depth/image_raw', 10)")
p()
p("        def publish_depth(self, path):")
p("            depth = cv2.imread(path, cv2.IMREAD_UNCHANGED)  # MUST use UNCHANGED!")
p("            if depth is None:")
p("                self.get_logger().error(f'Failed to read: {path}')")
p("                return")
p("            msg = self.bridge.cv2_to_imgmsg(depth, encoding='16UC1')")
p("            self.pub.publish(msg)")
p()
p("  Resulting sensor_msgs/Image fields:")
p("    header.frame_id: 'camera_depth_optical_frame'")
p("    height: 600")
p("    width: 800")
p("    encoding: '16UC1'")
p("    is_bigendian: 0")
p("    step: 1600")
p("    data: <960000 bytes, little-endian uint16>")

p()
p("SECTION 5: cv_bridge - DEPTH FROM sensor_msgs/Image")
p("-" * 80)
p()
p("  Subscribing to depth in ROS:")
p()
p("    class DepthSubscriber(Node):")
p("        def __init__(self):")
p("            super().__init__('depth_subscriber')")
p("            self.bridge = CvBridge()")
p("            self.sub = self.create_subscription(")
p("                Image, '/camera/depth/image_raw', self.callback, 10)")
p()
p("        def callback(self, msg):")
p("            depth = self.bridge.imgmsg_to_cv2(msg, desired_encoding='16UC1')")
p("            # depth.shape = (600, 800), depth.dtype = uint16")
p("            # depth values in mm")
p()
p("            # Convert to meters for ROS convention")
p("            depth_m = depth.astype(np.float32) / 1000.0")
p()
p("            # Publish as 32FC1 (float, meters)")
p("            msg_float = self.bridge.cv2_to_imgmsg(depth_m, encoding='32FC1')")

p()
p("SECTION 6: CAMERA INFO PUBLICATION")
p("-" * 80)
p()
p("  Reading BOP cam_K and publishing as CameraInfo:")
p()
p("    from sensor_msgs.msg import CameraInfo")
p("    import json")
p()
p("    def load_camera_info(scene_camera_path, frame_id):")
p("        with open(scene_camera_path) as f:")
p("            sc = json.load(f)")
p("        cam = sc[str(frame_id)]")
p("        K = cam['cam_K']  # [fx,0,cx,0,fy,cy,0,0,1]")
p()
p("        info = CameraInfo()")
p("        info.header.frame_id = 'camera_depth_optical_frame'")
p("        info.height = 600")
p("        info.width = 800")
p("        info.distortion_model = 'plumb_bob'")
p("        info.d = []  # no distortion")
p("        info.k = [K[0], K[1], K[2], K[3], K[4], K[5], K[6], K[7], K[8]]")
p("        info.r = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]")
p("        info.p = [K[0], K[1], K[2], 0.0,")
p("                  K[3], K[4], K[5], 0.0,")
p("                  K[6], K[7], K[8], 0.0]")
p("        return info")

p()
p("SECTION 7: 6DoF POSE PUBLISHING")
p("-" * 80)
p()
p("  Converting BOP GT to ROS PoseStamped:")
p()
p("    from geometry_msgs.msg import PoseStamped")
p("    import numpy as np")
p()
p("    def bop_to_pose(scene_gt_path, frame_id, obj_id=1):")
p("        with open(scene_gt_path) as f:")
p("            sg = json.load(f)")
p("        gt = sg[str(frame_id)][0]")
p()
p("        R = np.array(gt['cam_R_m2c']).reshape(3, 3)")
p("        t = np.array(gt['cam_t_m2c'])  # mm")
p()
p("        # Convert mm to meters for ROS")
p("        t_m = t / 1000.0")
p()
p("        pose = PoseStamped()")
p("        pose.header.frame_id = 'camera_depth_optical_frame'")
p()
p("        pose.pose.position.x = float(t_m[0])")
p("        pose.pose.position.y = float(t_m[1])")
p("        pose.pose.position.z = float(t_m[2])")
p()
p("        # Rotation matrix to quaternion")
p("        from scipy.spatial.transform import Rotation")
p("        quat = Rotation.from_matrix(R).as_quat()  # [x, y, z, w]")
p("        pose.pose.orientation.x = float(quat[0])")
p("        pose.pose.orientation.y = float(quat[1])")
p("        pose.pose.orientation.z = float(quat[2])")
p("        pose.pose.orientation.w = float(quat[3])")
p()
p("        return pose")

p()
p("SECTION 8: depth_image_proc PIPELINE")
p("-" * 80)
p()
p("  Launch depth_image_proc for point cloud generation:")
p()
p("    # Launch file: huhb3d_depth.launch.py")
p("    from launch import LaunchDescription")
p("    from launch_ros.actions import Node")
p()
p("    def generate_launch_description():")
p("        return LaunchDescription([")
p("            Node(")
p("                package='depth_image_proc',")
p("                executable='depth_image_proc',")
p("                name='depth_image_proc',")
p("                remappings=[")
p("                    ('image_raw', '/camera/depth/image_raw'),")
p("                    ('camera_info', '/camera/depth/camera_info'),")
p("                ],")
p("                output='screen'),")
p("        ])")
p()
p("  This converts 16UC1 depth + CameraInfo -> PointCloud2")
p("  Zero pixels (background) are automatically filtered")

p()
p("SECTION 9: COMMON PITFALLS REFERENCE TABLE")
p("-" * 80)
p()
p("  +----+----------------------------------+---------------------------+---------------------------+")
p("  | #  | Pitfall                          | Symptom                   | Fix                       |")
p("  +----+----------------------------------+---------------------------+---------------------------+")
p("  | 1  | cv2.imread() without             | Black image, values 2-3   | Use cv2.IMREAD_UNCHANGED  |")
p("  |    | IMREAD_UNCHANGED                 | instead of 730-844        |                           |")
p("  +----+----------------------------------+---------------------------+---------------------------+")
p("  | 2  | cv2.imshow() with uint16         | Black image (730/65535    | Normalize to 0-255 first  |")
p("  |    |                                  | looks near-zero)          | or use applyColorMap      |")
p("  +----+----------------------------------+---------------------------+---------------------------+")
p("  | 3  | cv_bridge encoding='mono16'      | May work but '16UC1' is   | Use encoding='16UC1'      |")
p("  |    | instead of '16UC1'               | the ROS standard          |                           |")
p("  +----+----------------------------------+---------------------------+---------------------------+")
p("  | 4  | Forgetting mm->m conversion      | Depth 800x too large      | Divide by 1000.0          |")
p("  |    |                                  | for point cloud           |                           |")
p("  +----+----------------------------------+---------------------------+---------------------------+")
p("  | 5  | Not handling zero (background)   | Background appears as     | Mask depth > 0 or use     |")
p("  |    | pixels                           | 0m depth point cloud      | depth_image_proc          |")
p("  +----+----------------------------------+---------------------------+---------------------------+")
p("  | 6  | cam_K as flat array not 3x3      | Wrong camera matrix       | np.array(K).reshape(3,3)  |")
p("  |    |                                  | shape                     |                           |")
p("  +----+----------------------------------+---------------------------+---------------------------+")
p("  | 7  | OpenGL vs OpenCV coordinates     | Pose appears flipped      | Our data is already in    |")
p("  |    |                                  |                           | OpenCV convention         |")
p("  +----+----------------------------------+---------------------------+---------------------------+")
p("  | 8  | is_bigendian=1 on x86            | Byte-swapped depth        | Set is_bigendian=0        |")
p("  |    |                                  | values                    | (cv_bridge default)       |")
p("  +----+----------------------------------+---------------------------+---------------------------+")

p()
p("SECTION 10: COMPLETE ROS2 NODE TEMPLATE")
p("-" * 80)
p()
p("  # huhb3d_ros_publisher.py")
p("  import rclpy")
p("  from rclpy.node import Node")
p("  from sensor_msgs.msg import Image, CameraInfo")
p("  from geometry_msgs.msg import PoseStamped")
p("  from cv_bridge import CvBridge")
p("  import cv2, json, numpy as np")
p("  from scipy.spatial.transform import Rotation")
p()
p("  class Huhb3DPublisher(Node):")
p("      def __init__(self, dataset_path, obj_name='flange'):")
p("          super().__init__('huhb3d_publisher')")
p("          self.bridge = CvBridge()")
p("          self.obj_dir = f'{dataset_path}/{obj_name}'")
p("          self.frame = 1")
p()
p("          self.rgb_pub = self.create_publisher(Image, '/camera/rgb/image_raw', 10)")
p("          self.depth_pub = self.create_publisher(Image, '/camera/depth/image_raw', 10)")
p("          self.info_pub = self.create_publisher(CameraInfo, '/camera/depth/camera_info', 10)")
p("          self.pose_pub = self.create_publisher(PoseStamped, '/object/pose', 10)")
p()
p("          self.timer = self.create_timer(0.5, self.publish_frame)")
p()
p("      def publish_frame(self):")
p("          f = str(self.frame)")
p()
p("          # RGB")
p("          rgb = cv2.imread(f'{self.obj_dir}/rgb/rgb_{self.frame:04d}.png')")
p("          if rgb is not None:")
p("              self.rgb_pub.publish(self.bridge.cv2_to_imgmsg(rgb, 'bgr8'))")
p()
p("          # Depth - MUST use IMREAD_UNCHANGED!")
p("          depth = cv2.imread(f'{self.obj_dir}/depth/depth_{self.frame:04d}.png',")
p("                             cv2.IMREAD_UNCHANGED)")
p("          if depth is not None:")
p("              self.depth_pub.publish(self.bridge.cv2_to_imgmsg(depth, '16UC1'))")
p()
p("          # Camera Info")
p("          with open(f'{self.obj_dir}/scene_camera.json') as fp:")
p("              sc = json.load(fp)")
p("          K = sc[f]['cam_K']")
p("          info = CameraInfo()")
p("          info.header.frame_id = 'camera_depth_optical_frame'")
p("          info.height, info.width = 600, 800")
p("          info.k = [float(x) for x in K]")
p("          info.p = [K[0],K[1],K[2],0, K[3],K[4],K[5],0, K[6],K[7],K[8],0]")
p("          self.info_pub.publish(info)")
p()
p("          # 6DoF Pose")
p("          with open(f'{self.obj_dir}/scene_gt.json') as fp:")
p("              sg = json.load(fp)")
p("          gt = sg[f][0]")
p("          R = np.array(gt['cam_R_m2c']).reshape(3,3)")
p("          t = np.array(gt['cam_t_m2c']) / 1000.0")
p("          pose = PoseStamped()")
p("          pose.header.frame_id = 'camera_depth_optical_frame'")
p("          pose.pose.position.x, pose.pose.position.y, pose.pose.position.z = t")
p("          q = Rotation.from_matrix(R).as_quat()")
p("          pose.pose.orientation.x, pose.pose.orientation.y = q[0], q[1]")
p("          pose.pose.orientation.z, pose.pose.orientation.w = q[2], q[3]")
p("          self.pose_pub.publish(pose)")
p()
p("          self.frame = self.frame % 10 + 1")
p()
p("  if __name__ == '__main__':")
p("      rclpy.init()")
p("      node = Huhb3DPublisher('/path/to/sell_Huhb3D-Test-Precision-v4')")
p("      rclpy.spin(node)")

p()
p("=" * 80)
p("  END OF ROS DEPLOYMENT MANUAL")
p("=" * 80)

with open(str(OUTPUT), "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"Saved: {OUTPUT}")
